project_id = "rrlisdmtvkexfsxgkali"

[functions.generate-recipes]
verify_jwt = false

[functions.analyze-preferences]
verify_jwt = false

[functions.generate-taste-profile]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false
